"""added bio column to authors

Revision ID: 3a3ca7c08651
Revises: f590de6db44e
Create Date: 2025-02-08 18:41:01.286479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a3ca7c08651"
down_revision: Union[str, None] = "f590de6db44e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_authors",
        sa.Column("bio", sa.Text(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_authors", "bio")
    # ### end Alembic commands ###
