"""create product table

Revision ID: 4d0aae4c4db9
Revises: 8a87cf7f9fc0
Create Date: 2025-02-14 19:05:09.056399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d0aae4c4db9"
down_revision: Union[str, None] = "8a87cf7f9fc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_products",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blog_products")
    # ### end Alembic commands ###
