"""Check missing migrations

Revision ID: f8877a12ec1a
Revises: 3a3ca7c08651
Create Date: 2025-02-08 20:35:42.485522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8877a12ec1a"
down_revision: Union[str, None] = "3a3ca7c08651"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_users",
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column(
            "is_staff", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "blog_authors",
        sa.Column(
            "name", sa.String(length=20), server_default="", nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("bio", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["blog_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "blog_posts",
        sa.Column(
            "title", sa.String(length=200), server_default="", nullable=False
        ),
        sa.Column("body", sa.Text(), server_default="", nullable=False),
        sa.Column("rating", sa.Integer(), server_default="0", nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["blog_authors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_blog_posts_title"), "blog_posts", ["title"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blog_posts_title"), table_name="blog_posts")
    op.drop_table("blog_posts")
    op.drop_table("blog_authors")
    op.drop_table("blog_users")
    # ### end Alembic commands ###
